[rpc]
url = "http://127.0.0.1:5050/rpc"

[sncast.account1]
account = "account1"
accounts-file = "/Users/daniel.kakai/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://localhost:5050/rpc"

[sncast.default]
account = "account1"
accounts-file = "/Users/daniel.kakai/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://localhost:5050/rpc"